// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "LcmBodyPose.h"

static int __LcmBodyPose_hash_computed;
static uint64_t __LcmBodyPose_hash;

uint64_t __LcmBodyPose_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __LcmBodyPose_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __LcmBodyPose_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x7c5dc0ffabd0d5e0LL
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __LcmBodyPose_get_hash(void)
{
    if (!__LcmBodyPose_hash_computed) {
        __LcmBodyPose_hash = (int64_t)__LcmBodyPose_hash_recursive(NULL);
        __LcmBodyPose_hash_computed = 1;
    }

    return __LcmBodyPose_hash;
}

int __LcmBodyPose_encode_array(void *buf, int offset, int maxlen, const LcmBodyPose *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].body_pos, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].body_ori_quat, 4);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int LcmBodyPose_encode(void *buf, int offset, int maxlen, const LcmBodyPose *p)
{
    int pos = 0, thislen;
    int64_t hash = __LcmBodyPose_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __LcmBodyPose_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __LcmBodyPose_encoded_array_size(const LcmBodyPose *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __float_encoded_array_size(p[element].body_pos, 3);

        size += __float_encoded_array_size(p[element].body_ori_quat, 4);

    }
    return size;
}

int LcmBodyPose_encoded_size(const LcmBodyPose *p)
{
    return 8 + __LcmBodyPose_encoded_array_size(p, 1);
}

int __LcmBodyPose_decode_array(const void *buf, int offset, int maxlen, LcmBodyPose *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].body_pos, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].body_ori_quat, 4);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __LcmBodyPose_decode_array_cleanup(LcmBodyPose *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_decode_array_cleanup(p[element].body_pos, 3);

        __float_decode_array_cleanup(p[element].body_ori_quat, 4);

    }
    return 0;
}

int LcmBodyPose_decode(const void *buf, int offset, int maxlen, LcmBodyPose *p)
{
    int pos = 0, thislen;
    int64_t hash = __LcmBodyPose_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __LcmBodyPose_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int LcmBodyPose_decode_cleanup(LcmBodyPose *p)
{
    return __LcmBodyPose_decode_array_cleanup(p, 1);
}

int __LcmBodyPose_clone_array(const LcmBodyPose *p, LcmBodyPose *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_clone_array(p[element].body_pos, q[element].body_pos, 3);

        __float_clone_array(p[element].body_ori_quat, q[element].body_ori_quat, 4);

    }
    return 0;
}

LcmBodyPose *LcmBodyPose_copy(const LcmBodyPose *p)
{
    LcmBodyPose *q = (LcmBodyPose*) malloc(sizeof(LcmBodyPose));
    __LcmBodyPose_clone_array(p, q, 1);
    return q;
}

void LcmBodyPose_destroy(LcmBodyPose *p)
{
    __LcmBodyPose_decode_array_cleanup(p, 1);
    free(p);
}

int LcmBodyPose_publish(lcm_t *lc, const char *channel, const LcmBodyPose *p)
{
      int max_data_size = LcmBodyPose_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = LcmBodyPose_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _LcmBodyPose_subscription_t {
    LcmBodyPose_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void LcmBodyPose_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    LcmBodyPose p;
    memset(&p, 0, sizeof(LcmBodyPose));
    status = LcmBodyPose_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding LcmBodyPose!!!\n", status);
        return;
    }

    LcmBodyPose_subscription_t *h = (LcmBodyPose_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    LcmBodyPose_decode_cleanup (&p);
}

LcmBodyPose_subscription_t* LcmBodyPose_subscribe (lcm_t *lcm,
                    const char *channel,
                    LcmBodyPose_handler_t f, void *userdata)
{
    LcmBodyPose_subscription_t *n = (LcmBodyPose_subscription_t*)
                       malloc(sizeof(LcmBodyPose_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 LcmBodyPose_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg LcmBodyPose LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int LcmBodyPose_subscription_set_queue_capacity (LcmBodyPose_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int LcmBodyPose_unsubscribe(lcm_t *lcm, LcmBodyPose_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe LcmBodyPose_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

